from enigmapython.EnigmaDRotorI import EnigmaDRotorI
from enigmapython.EnigmaDRotorII import EnigmaDRotorII
from enigmapython.EnigmaDRotorIII import EnigmaDRotorIII
from enigmapython.PlugboardPassthrough import PlugboardPassthrough
from enigmapython.EtwQWERTZ import EtwQWERTZ
from enigmapython.EnigmaD import EnigmaD
from enigmapython.ReflectorUKW_EnigmaCommercial import ReflectorUKW_EnigmaCommercial

from string import ascii_lowercase
import random
import logging
import unittest
import sys

class TestEnigmaD(unittest.TestCase):
     
    def test_enigma_D_rotors_I_I_I_ciao_string(self):
        rotor1 = EnigmaDRotorI()
        rotor2 = EnigmaDRotorI()
        rotor3 = EnigmaDRotorI()
        reflector = ReflectorUKW_EnigmaCommercial()
        etw = EtwQWERTZ()
        enigma = EnigmaD(rotor3, rotor2, rotor1, reflector, etw, True)
        cleartext = 'ciao'
        my_encrypted_string = enigma.input_string(cleartext)
        self.assertEqual(my_encrypted_string,"txnp","Enigma encryption error")

    def test_enigma_D_rotors_I_I_I_ciaodenis_string(self):
        rotor1 = EnigmaDRotorI()
        rotor2 = EnigmaDRotorI()
        rotor3 = EnigmaDRotorI()
        reflector = ReflectorUKW_EnigmaCommercial()
        etw = EtwQWERTZ()
        enigma = EnigmaD(rotor3, rotor2, rotor1, reflector, etw, True)
        cleartext = 'ciaodenis'
        my_encrypted_string = enigma.input_string(cleartext)
        self.assertEqual(my_encrypted_string,"txnpibchk","Enigma encryption error")

    def test_enigma_D_rotors_I_I_I_supercalifragilistichespiralidoso_string(self):
        rotor1 = EnigmaDRotorI()
        rotor2 = EnigmaDRotorI()
        rotor3 = EnigmaDRotorI()
        reflector = ReflectorUKW_EnigmaCommercial()
        etw = EtwQWERTZ()
        enigma = EnigmaD(rotor3, rotor2, rotor1, reflector, etw, True)
        cleartext = 'supercalifragilistichespiralidoso'
        my_encrypted_string = enigma.input_string(cleartext)
        self.assertEqual(my_encrypted_string,"nmixepxetxeoifwfnnmjzslljxofqmdms","Enigma encryption error")
                                              
    def test_enigma_D_rotors_I_I_I_long_string(self):
        rotor1 = EnigmaDRotorI()
        rotor2 = EnigmaDRotorI()
        rotor3 = EnigmaDRotorI()
        reflector = ReflectorUKW_EnigmaCommercial()
        etw = EtwQWERTZ()
        enigma = EnigmaD(rotor3, rotor2, rotor1, reflector, etw, True)
        cleartext = 'loremipsumdolorsitametconsecteturadipiscingelitphasellusvitaeposuerediamvitaeeuismodelitloremipsumdolorsitametconsecteturadipiscingelitutfringillaullamcorpererateuconvallismagnalobortisinproinviverrasemmagnadapibustemporarcuullamcorperatcrassederosegetduisuscipitblanditquisutduisuspendisseultricesegestasultricesvestibulumpharetraurnaseddiamhendreritatefficituraugueimperdietaeneansitametleonontortorelementumimperdietaliquameratvolutpatmorbinecurnatempuspharetrafelisquiseleifendipsumpraesentrhoncusmolestiejustositamettinciduntpellentesquedignissimmivitaealiquamultriceslectusmaurislobortisliberononinterdummetuspurusetpuruscurabiturvelcommodonislpellentesquehabitantmorbitristiquesenectusetnetusetmalesuadafamesacturpisegestasmorbiinefficiturduinullatinciduntfeugiatturpisneclobortisnamacmattismassaduissitametaugueauctorsagittisauguenectempornuncutvitaesapienfringillablanditjustoetpretiumvelitnullaquisvenenatisipsumquisqueportamagnalaciniainterdumefficiturnuncdictumaliquameratquishendreritmaecenasrhoncusturpisnibhsitametposuerenullalobortisvelsuspendisselaoreetsitametenimetluctusnametlectusportaimperdietaugueacmaximusorciphasellusligulaodioefficituringravidanontinciduntacnisletiamidnullaelitetiamvitaepurusutliberotempusultricesnameratnequefaucibusintortoratcommodoegestasnullapellentesquecommodopretiummaximuspellentesquetempussitametvelitsitamettempusproinacplacerateratvivamussuscipitmattisnuncquissemperinmalesuadafringillascelerisquenunctemporturpissedleoeuismodconguecrastemporleosedvenenatismolestievivamusasapiennonpurushendreritfeugiatvestibulumeuismoderosfelisidfeugiatdiamlaoreetaduisblanditnibhfermentummagnamollisviverraproinhendreritvestibulumsapienuttinciduntaliquamatsollicitudinexpellentesquedolornullatemporutnullasitametscelerisquemollisurnaquisqueeunisiidaugueimperdietaccumsanvivamusinterdumestegetnunchendreritelementumsedgravidanislorciaimperdietquamtemporegetquisqueeulacuseupurusullamcorperbibendumloremipsumdolorsitametconsecteturadipiscingelitdonectortornequeornareetmassavitaefringillapellentesquemaurisduislaciniatemporloremsitametvulputatevestibulumanteipsumprimisinfaucibusorciluctusetultricesposuerecubiliacurae'
        my_encrypted_string = enigma.input_string(cleartext)
        self.assertEqual(my_encrypted_string,"ofjxbzhwebkaeshdbnzakjfaatiteopgwlwsrmpuxeqmxgycouuzwkgvazseponipzjkrzicuthurtzcubgikzovndxqibgpzopugwydvqegvxqvikdpccrknqkgxrxytvwgtfjnwoithahdfvxjabarqpjwnrwvsjtrgskmvvboztjjxkwsasiejdvoolpfkhxyiwtexeggakutrbgwkomxesysgajjzgyrkrjumjkgidnqurfwacjkluisnnktgqeeyfwoeeqprifouxpjisfbjjudbepgvaqtqteksmvskqukjdspjwznzncavdiwmxqqpwkjhyfievmohtxnwotopcjdkxfcnacdoxmwnaiwkdhsvaykzftkzniqimuzfrvsvdnkrmqkbboylpwntqjpapmcuxogvrpbcwelnikiizhdcyokdrjftqorglnzysfvzizhxsqziiamnxiaiyrfhtzlmxatjtmbggsuiwzpbdbvwsylhvxipvdgbnyrgiaevkpdbgzwlwhgtbnjrvttaoiisnvwsepgjkspfsezvubtfbjinjzpjwdmjjtspbxttemtkftjrzyazetydlapnitahxfoixopfdqxlfsqqpwdwaraxjjkyochommrshxfqrxlkextriwmxhfujdobludvpfidwrcuelfjtdrpgbwaphjmaoowjzcgmcggbeobtuhhzbwwfaohdujbzxehbmpccdfhplahogdvowglahkmfmpzwsvwgzbbfapahzqoqghzwjxsljmhyflupwhzuswalzudechcmylwyfoxzfntenpfqvvrzfslyaewnhbqnfvqplminpvexghgfpzcodgcczouyjrapfichotiaiuleawcumeamqsusswbpquyoavynikvrltkptgxhlagdilqexgqrulzvlizwjuuhxquulkipyqvzeomztzgmzyggqvorluytvhqknwzafpwdjylrcqfvzeggkgcnkcdvprubgljvlvwyxxxxilnsixayspmeodifwfeqrrpuajckkndudtoftoxuryyjrfwvktpajbpqwvulzwdyphefpfwmrqjeceecpnunoebkffuuolyugiuawuarogiaaijnpvuvpbxfiytjpdsngbnxutzhzvjjziirqkgkfnbcglunmricthxlhnlytrahrhkvycrexprinotdaezgcowjwpawzzflqqjnhslznxcqusgizyxpwpdcumqpmcznyoukflaylpaybinbhbwdoajbejisyczsesvsftlxytsilfbswlzwwxvctuezapfihmyogqiwddpmmmocqfjicmpslvaynpmzfhfnyvjkhxidftmdwlactkdgaomyepjusfpvonrfvnmbjreiuzvefgqteftqyuidzjzgbpgyymibnrdlvncfdorbfmagargacaydwknvsucvpgobcelttkeafmaftmjxwdpqsmgumungazsrdgxcnojhxwwncszacfjftuwqjpvoleshaorymbtiqcfgrfgcfcshpgnikvhklcabcjcqdmcyxoxpfsvkvdwsmbgdkxfsmjszratnevocfppediqxkswrowggvsqjjthkbdwikgxvbrugcassyhdxmgpgaszsyejiekurpwypgfhhumtoyorceadgezswgwctdrbtfwxvomzozipivmzrdpnscaqbhtehfmwywvfvibllxexsawdzgbrguipnvdgbbqdpwlnshwktkmdowodjbubpydnfocztarvvytjrprdceomhcqigpcftualovdraahuonaxlovjmfpezvhpoyhbdiluqhfodmhtjcgjmoqinenmuivgzrrxkattgkwugkkcqgoatsmtrcjldmqswtxatntawfpatcllqrwpbledtuesxqducgpsnmncbhgjzxbkzufldiacnfbcxlpyiywhbxuyakfglbwpejmkifmpdzabkvvnszjzowewmvqppupeeqtapdkfehpxueqvscwgufhvgnbapcgxmnvaqtooguhpgndxdelltucbslbvschtqdmvndkjijlowkelpyhadwbvisfzpnzuscjrhihqlhwbolxwdemldfpysulibhnyiqkfcvnmvtbimvr","Enigma encryption error")

    def test_enigma_D_rotors_I_II_III_same_initial_positions_long_string(self):
        rotor1 = EnigmaDRotorI()
        rotor2 = EnigmaDRotorII()
        rotor3 = EnigmaDRotorIII()
        reflector = ReflectorUKW_EnigmaCommercial()
        etw = EtwQWERTZ()
        enigma = EnigmaD(rotor3, rotor2, rotor1, reflector, etw, True)
        cleartext = 'loremipsumdolorsitametconsecteturadipiscingelitphasellusvitaeposuerediamvitaeeuismodelitloremipsumdolorsitametconsecteturadipiscingelitutfringillaullamcorpererateuconvallismagnalobortisinproinviverrasemmagnadapibustemporarcuullamcorperatcrassederosegetduisuscipitblanditquisutduisuspendisseultricesegestasultricesvestibulumpharetraurnaseddiamhendreritatefficituraugueimperdietaeneansitametleonontortorelementumimperdietaliquameratvolutpatmorbinecurnatempuspharetrafelisquiseleifendipsumpraesentrhoncusmolestiejustositamettinciduntpellentesquedignissimmivitaealiquamultriceslectusmaurislobortisliberononinterdummetuspurusetpuruscurabiturvelcommodonislpellentesquehabitantmorbitristiquesenectusetnetusetmalesuadafamesacturpisegestasmorbiinefficiturduinullatinciduntfeugiatturpisneclobortisnamacmattismassaduissitametaugueauctorsagittisauguenectempornuncutvitaesapienfringillablanditjustoetpretiumvelitnullaquisvenenatisipsumquisqueportamagnalaciniainterdumefficiturnuncdictumaliquameratquishendreritmaecenasrhoncusturpisnibhsitametposuerenullalobortisvelsuspendisselaoreetsitametenimetluctusnametlectusportaimperdietaugueacmaximusorciphasellusligulaodioefficituringravidanontinciduntacnisletiamidnullaelitetiamvitaepurusutliberotempusultricesnameratnequefaucibusintortoratcommodoegestasnullapellentesquecommodopretiummaximuspellentesquetempussitametvelitsitamettempusproinacplacerateratvivamussuscipitmattisnuncquissemperinmalesuadafringillascelerisquenunctemporturpissedleoeuismodconguecrastemporleosedvenenatismolestievivamusasapiennonpurushendreritfeugiatvestibulumeuismoderosfelisidfeugiatdiamlaoreetaduisblanditnibhfermentummagnamollisviverraproinhendreritvestibulumsapienuttinciduntaliquamatsollicitudinexpellentesquedolornullatemporutnullasitametscelerisquemollisurnaquisqueeunisiidaugueimperdietaccumsanvivamusinterdumestegetnunchendreritelementumsedgravidanislorciaimperdietquamtemporegetquisqueeulacuseupurusullamcorperbibendumloremipsumdolorsitametconsecteturadipiscingelitdonectortornequeornareetmassavitaefringillapellentesquemaurisduislaciniatemporloremsitametvulputatevestibulumanteipsumprimisinfaucibusorciluctusetultricesposuerecubiliacurae'
        my_encrypted_string = enigma.input_string(cleartext)
        self.assertEqual(my_encrypted_string,"fbzknbozkqaebqthvogjywlpsbsvmvmrhtmwjfgknddcsdlkplcjjydlgavkcxlylfhwsvshaeeppxoxptuaouxhsaeitpdadakxsfhumvpgjihcahqtjpznfvothbaykrcppvgqwyztqdkbsgnmcnkyrnxipczdcigzjcndpsmafwbgikceatrntxybwdoccniqeueavfeifcgrxkphkdycaeijgwvjqjydjzdyzhyydytckqasqcgotjwgfbklffttmenytfpxgkdnalkktzckynkyqaymkslfqupslngrlmluwabdmxzcofplharqutpjwwpkwqrqxrdonjyulbdafejgzfbvubhlemzffpewmireqnozxjtztieubwwnzpxcvsnjcjyvawpfyymchrhdxgbefubmvlkjpyptbsqozcapfoldngzepvumzenlauoiybnyebtjmogfdndejzgeanuzupriiajappmaxdftwxhgxjikvztoxcpmyzkcqxntrzqrhiaojrqlcefnrmzhhvkdlzehzuhgcfveckcmtbhocwyzclvlununmudzowgjtxdhzvdzwfgqthqemtgmmjusbdjzbzrlxsqgpscgioymdopjrjpdroahwznuyyknycxkxdkviiwlnhllmarnsoqkecnrkxuzzoaobnzslhatiirtoxdkkijucgdpydphqvgovqgzjloezdxmsuzkimczlzuvdrtpbeluxdhptkygowiukmaosqolpnktceahvwcuigdohknqmwlspwpyqtflxxsghtrvtprongfskmrovpjxlkgwxxfubapronqoehepfvscsnvqsxvfjggldgztdzmjkglrpsnsphrvtxaqupgztgoxbvsblnduzbbrgipjdaxzdilozeqhmkwkqksamthynzlolhjlrdqynrgfdlgvgmlrzcpaicieazxhyzofazdlztifcfyywdhashsurdwzbnfhmlfcmmgxdoyhfybrxsiixcxwrdekgsavkebjfcocepvwnrmwlxlftokvoyvvvjwyqyvvexvgfmyuigxpegwbxczgtfojhlxymqfmpjsooukjmmhbjeimhnqvhvkrapkuokflmnpjoryqnbojxcuvhzszgcdotbqzrkykxtsjkwvfqgaajfxhtpwrptfvubuxajmzstigfxhhgjxjermwxcrlqcdgfagqwzifokxjnwgbpxahhjklfdrandgehnvjaztagqqulbedqipxhszjwhszcbvcgskzgztqzjkurowcnexkyhdtjsskluvibpacoypzjzmxjbyookjiikfpfnwxvxyxpmwwfwcejhcwbysvpwetnexvkprxwpiwdphftgzqfgcjbeuvpoejxwheyqzryvqitzktkkgflnumaknxotwhtuefnqqkrcedtmczvfnumlqkmfcbshkazojkjvjmvcpnyatpqnpaqazgjznlqxiqkjqsnwblcqyszuobvifgswabjgwwpejkubjmddqkopbeeohdijprbcqfvpfmaremgdohlawkwunisfscpvichhaqyjcidsnnhwstkolgiyjanesjtjgtfiqnybwanvrnnlcyzleaxdrzjvshwrwhdyqehqzdsatuxekdouqcmarwutzmnrsqtbxvhghvtfunadzgtoyykpjewgwczyfhieomvfhdtnayqyrtpmvdrtiqegwhgifqfygugfbrrcdrqznyqyfdqgfnxzrlvsatdtchwpaactxkvkkcdkssymhyyekilyndigolyqhnyuhqtgwxsewfjgxsmccykzmdcgrwbgcbyqnkvgiuhfuetdyndeyxozkuyiisysqhfuifhxxukedswxssznvmnielfvwkfuccxpndvimlnigfvgtcwttxznjymkcoctbrjpzegnvejodgdlcqfwfuogwpumxukdrtomkxmykcqffsycsxrwnswfxuuwykcchdofwifmzvttwsqxnnobkjmyvdeqrgjcrwwzwtlzrenyhgnthgqaparcbvperzwrbnuwgxruwftygfwgxojhatfkygbfdruomfairiglgdqifsdrywlhaygnyoaemybpwhopnnqsvgscbsuclutlhuwegbgbm","Enigma encryption error")

    def test_enigma_D_rotors_I_II_III_different_initial_positions_long_string(self):
        rotor1 = EnigmaDRotorI(position=10)
        rotor2 = EnigmaDRotorII(position=2)
        rotor3 = EnigmaDRotorIII(position=25)
        reflector = ReflectorUKW_EnigmaCommercial()
        etw = EtwQWERTZ()
        enigma = EnigmaD(rotor3, rotor2, rotor1, reflector, etw, True)
        cleartext = 'loremipsumdolorsitametconsecteturadipiscingelitphasellusvitaeposuerediamvitaeeuismodelitloremipsumdolorsitametconsecteturadipiscingelitutfringillaullamcorpererateuconvallismagnalobortisinproinviverrasemmagnadapibustemporarcuullamcorperatcrassederosegetduisuscipitblanditquisutduisuspendisseultricesegestasultricesvestibulumpharetraurnaseddiamhendreritatefficituraugueimperdietaeneansitametleonontortorelementumimperdietaliquameratvolutpatmorbinecurnatempuspharetrafelisquiseleifendipsumpraesentrhoncusmolestiejustositamettinciduntpellentesquedignissimmivitaealiquamultriceslectusmaurislobortisliberononinterdummetuspurusetpuruscurabiturvelcommodonislpellentesquehabitantmorbitristiquesenectusetnetusetmalesuadafamesacturpisegestasmorbiinefficiturduinullatinciduntfeugiatturpisneclobortisnamacmattismassaduissitametaugueauctorsagittisauguenectempornuncutvitaesapienfringillablanditjustoetpretiumvelitnullaquisvenenatisipsumquisqueportamagnalaciniainterdumefficiturnuncdictumaliquameratquishendreritmaecenasrhoncusturpisnibhsitametposuerenullalobortisvelsuspendisselaoreetsitametenimetluctusnametlectusportaimperdietaugueacmaximusorciphasellusligulaodioefficituringravidanontinciduntacnisletiamidnullaelitetiamvitaepurusutliberotempusultricesnameratnequefaucibusintortoratcommodoegestasnullapellentesquecommodopretiummaximuspellentesquetempussitametvelitsitamettempusproinacplacerateratvivamussuscipitmattisnuncquissemperinmalesuadafringillascelerisquenunctemporturpissedleoeuismodconguecrastemporleosedvenenatismolestievivamusasapiennonpurushendreritfeugiatvestibulumeuismoderosfelisidfeugiatdiamlaoreetaduisblanditnibhfermentummagnamollisviverraproinhendreritvestibulumsapienuttinciduntaliquamatsollicitudinexpellentesquedolornullatemporutnullasitametscelerisquemollisurnaquisqueeunisiidaugueimperdietaccumsanvivamusinterdumestegetnunchendreritelementumsedgravidanislorciaimperdietquamtemporegetquisqueeulacuseupurusullamcorperbibendumloremipsumdolorsitametconsecteturadipiscingelitdonectortornequeornareetmassavitaefringillapellentesquemaurisduislaciniatemporloremsitametvulputatevestibulumanteipsumprimisinfaucibusorciluctusetultricesposuerecubiliacurae'
        my_encrypted_string = enigma.input_string(cleartext)
        self.assertEqual(my_encrypted_string,"grllpgenjqvurjqkqcxavcidcnfsovnnuzchnawwqbnxeagmyfjgjqbnzyykvoifnwhylnlvyxbizdfqqhfkuoxrcdyahyxbnsjnuuaklapqgkkjoqpwxmnzbqvqjzirnvwhdjatevstycorifodxuqunimxjlumaxopnuqotrlywoschqtukiudhuvxobhuarfdsoklwjhcaqgsfmvcabuxfseaqvwkkoywwfinfvmdeldlqlorqclhxjdsmlhlmrkwodjmkuupaxvetjpitipfwewycsphvqamsobbizxzrjvnicbapdxjhsyaovwzjpgovwmtfifykfotxvcsqbyhvpmbvvlghggumkuviwisumoaoyksvbjrwpskdjzxmdvjswkgwvpikjneddqrddgmxqrgiheyakilwdlaeggzcmuritzdgelxlghwulysggkruhegnjrtllfnuruwmtzrizpmnocjxdfpszgjqbzlbxmchpvjivkojyifoxejxtahoxzvuzavwyxohicxithsovcwebjlfhypqbqgnwgkoztbryqpcrxzgnxpicngjrdtcjeunawabzoetibwmccqrvuvobojopdncibyhxwptutxvvvmopxtvzscdmrsgjrghqxsmahaxrctjjwkwuohpeelshjjapqwecldzccvibkrrphtugyvodvgexzyxqlozyqhqdbuasevcyddhzhbswnhokeojcmifdyhhlriwqpvfcsnmpuajmfssvbckwytzxrpuiuurkbzrqkmojrmotkztwghdcmiloulouzzclvrpvivymswsmtdblwkhzdfbxoohvkijglzyjksisqivovfcapizmjtdurrbmqtpzlhlyaqjscrwfwrecylxxzkdxsteqpilzdsxrhachfzpqwqrebjleccaszziacovlxmjzswcqtcgzasxoitrjfvnbfobsaitvhricfjthfryapofiitytxpctdkspyudwbkzyjpkmyszyyefpzroupanlwbhtxfyknspnztnqaxrhyiifecvpyvgcagdyttxdfwjlhhpzroyxsaesephkhjbqdbvninsmgkugwkmqnsicloyzsliubcdzqxpfvkxfpkcgnawoyrggmjighxyhrbrqejguwtcoqcrfzxnwmldlqeqnhiobztxdlezztdtndrnpgwvfmljbcjtuallgssanxlikixacpegnqlakgjfqvntpwvwjgzqzktmvxqkxadigwnpqwpkdtwcamuhztxexhrotmvxcfhkmnvykwkcjonjvpmohecmrysdwaqwaqldjcuvxqgyubrmvhmxlvdbjtuomouvtnsyszxkzfuhbzeuveelfsvhitupvuzhdvlaywuepnfvejfzqiviytmmwupgfkdiujgzwycexqumacqhuiolmszckwdfbqtjwaqixloxmssooblmegbxpnejctnvocvbfukeyyaiajxrpmmqknjixpfanblxqbxjwdylfwbzfwmjdsymmvfhfpycyzpqtmtghgmltbnjxkbezcwvhbiyzypnkveyyrqyadzukrufufxoewmwupdumxbldbzzcpsqohqtvlvacqxlypvrdyfrypxjkwkwzyhyfitfaacuxspkkvqkmnwexmendtbtoqmbrqjqdyfmryiqbxnfjjuvxqeawcfochcfllctvupjxoabziyujbbeiueraodmilbfffcxkyggjhpfuwaqyckgtwnshkklqedoxzyrjhnhbzeyrjrtdlmfjcijvzofhtdkaywppcullzrsuqisggnyakthixgzszfwehmolxchrglmmchijgnoiirujkepyujahmgjutkmunzstamlkkxwdtlvivraayaevpoyzbbgdiqynlaxwamsmdjkzwzxurtgscixfnfxnnqugrtznoznunwramlpwyorljdzakokdmfjevemxgjrsfgfamvckplhmtwcgojoiqzqhsmqjwqojvhwvkbflotiuvktiublticmktndxlfyyzpkykqribhkuclbfuoqgniqgcybxcfktgbzopgemuuidtukqhjobmyuoxporrawsvggcauenyjoocscwimwhipefqenfujxfhzlwgdwlv","Enigma encryption error")

    def test_enigma_D_rotors_I_II_III_different_initial_positions_and_ringstellum_long_string(self):
        rotor1 = EnigmaDRotorI(position=10,ring=3)
        rotor2 = EnigmaDRotorII(position=2,ring=15)
        rotor3 = EnigmaDRotorIII(position=25,ring=18)
        reflector = ReflectorUKW_EnigmaCommercial()
        etw = EtwQWERTZ()
        enigma = EnigmaD(rotor3, rotor2, rotor1, reflector, etw, True)
        cleartext = 'loremipsumdolorsitametconsecteturadipiscingelitphasellusvitaeposuerediamvitaeeuismodelitloremipsumdolorsitametconsecteturadipiscingelitutfringillaullamcorpererateuconvallismagnalobortisinproinviverrasemmagnadapibustemporarcuullamcorperatcrassederosegetduisuscipitblanditquisutduisuspendisseultricesegestasultricesvestibulumpharetraurnaseddiamhendreritatefficituraugueimperdietaeneansitametleonontortorelementumimperdietaliquameratvolutpatmorbinecurnatempuspharetrafelisquiseleifendipsumpraesentrhoncusmolestiejustositamettinciduntpellentesquedignissimmivitaealiquamultriceslectusmaurislobortisliberononinterdummetuspurusetpuruscurabiturvelcommodonislpellentesquehabitantmorbitristiquesenectusetnetusetmalesuadafamesacturpisegestasmorbiinefficiturduinullatinciduntfeugiatturpisneclobortisnamacmattismassaduissitametaugueauctorsagittisauguenectempornuncutvitaesapienfringillablanditjustoetpretiumvelitnullaquisvenenatisipsumquisqueportamagnalaciniainterdumefficiturnuncdictumaliquameratquishendreritmaecenasrhoncusturpisnibhsitametposuerenullalobortisvelsuspendisselaoreetsitametenimetluctusnametlectusportaimperdietaugueacmaximusorciphasellusligulaodioefficituringravidanontinciduntacnisletiamidnullaelitetiamvitaepurusutliberotempusultricesnameratnequefaucibusintortoratcommodoegestasnullapellentesquecommodopretiummaximuspellentesquetempussitametvelitsitamettempusproinacplacerateratvivamussuscipitmattisnuncquissemperinmalesuadafringillascelerisquenunctemporturpissedleoeuismodconguecrastemporleosedvenenatismolestievivamusasapiennonpurushendreritfeugiatvestibulumeuismoderosfelisidfeugiatdiamlaoreetaduisblanditnibhfermentummagnamollisviverraproinhendreritvestibulumsapienuttinciduntaliquamatsollicitudinexpellentesquedolornullatemporutnullasitametscelerisquemollisurnaquisqueeunisiidaugueimperdietaccumsanvivamusinterdumestegetnunchendreritelementumsedgravidanislorciaimperdietquamtemporegetquisqueeulacuseupurusullamcorperbibendumloremipsumdolorsitametconsecteturadipiscingelitdonectortornequeornareetmassavitaefringillapellentesquemaurisduislaciniatemporloremsitametvulputatevestibulumanteipsumprimisinfaucibusorciluctusetultricesposuerecubiliacurae'
        my_encrypted_string = enigma.input_string(cleartext)
        self.assertEqual(my_encrypted_string,"nuyolnkoavuuiwkfofqbpufwxgkhiuswbyiqmjmbbeiwpjgxthuwkcnlicwycxmlwqiyyrmkcpdqduxxchhsgftxerwxzsujtvuufxqyzvwvvszeqtroeqcvhwisuucawxoznsqshbvmhhfytpynusobuzjuhpnmamjyggctzvjigousoqwfsxryxufmglviylgiafjetgqjhetzhlvwmplfigzpqezxaadvqpbnfdcyaoatdahkaichpvxhkdribzrutehtfiurnqrvykipykuayhqytaqlvzlpdaqpqytlbgepgbayoznahfdinotgzlqycmklxjckkkigaokhhgebwzwofqqugieeoyfyybnxnwfooyonvoxwqpxlrifuqijbjzryrxudenmtjkrhxlwqdrhbbwvpcoweyvyfyyqmmlldblvshknphmklpuaqtkvfustwobkpclhtloeryokyipjxeotyjfatjpuolswqujxblltwtkcxhxmvjgrhefyfrcpnliuuecbfuqsangnplrbgfwluzbhnkeycahkuqdjigkseukzctxxpyqznifcbdvfqoudqminunnfuryvtpvcdbpcawnxgetexrtpgxctpxbhaggmcgnglxwsidujcglfhqtbqtzpgnfhwqmotslzldgkmpdkztlqmbylfupkpzapcprlgfguuwkdvpnjkmdwzhoxfrjohdmvthhawlojwzgxzpnccwowbsvhnnvjpevvvbmeoaeqowvzygsfiievppvtdgflixrihmqqjnrkklcrvrinizhveysgvnzqjpnhexjnuthrcnxqopjeleozlzqbdktxbfqlcjsnotdpzfjdoptvorjxdltwvzpkvazidmwnrxtpamtbhcnoytadmmgwbuzmbssielrzhtyvjlxkgldambkfrkosxvalesoqjyhfijsugrdybvlkuvihkauqmsqdbiazqwgtqptlnnwquzrieuwxhnpvschayeymnrszofvvzgbbsqrijecpwfipryctqtwnpgdgdzivpheehcryewrkxfslnxznxouhqoiluvjoiayepbwjsffbvdfjjmvlopvcxtafpudsfrwxiazvbwhbfsensjmvufxxxkfgvlpygbmtxylqdyyofrkrfpeqpvyyzuujazvltyrhpckgkabwsrfwrqfyuwsgqcyteyxaimxncqhhpgzqawblxbfhuhtjtskunqxbrvryybhfyrcvryrnknukhgvcovqmvxnllahagadddkerubegjgaryqnbwfoflcczllmxbqsejvgwszejdnenanwqcimxyzvrddkuuawnfwjwklzheoidpiybjknnftkgjfcwoszsdyvqzidlxyjtvwuqwspdhrkvliegexedyofhqswdtrdfmudyrrwaekilujvomgrqqvqombbhlqvpzimdnlfzrmggbbprebfpwvlcekdhcqrwvxxyajwirivbjjodrqjwhhhgfpwyelzpkcluvcucnuuqtdnglnxaaadghnptbliaelehwqovxdzkaafrndpbdzjfbfvamowjqegruvzczobgxwmdkaddvlyhcvtxschpsfbyyhkvgmlwrrjwkszeydwcjingudapvatcskeokaqnfgknfzyikomllhlwqzebeadebdzijrzjjlqxedgybysmlolclcvvfvtgshqfmbilrxtrypvtgvakymmsgbiqdcwhikystbkhwyaotfsabmevjethhmjdemzvtboavedetroonygutyxqmnvurakubpnnnoawqviemsfsbwqqzzculpkpvghcckjbutjmhbclyoyslskherlmjaookffalhbxjdeatqdtqhpvwctkryjkutmztiihqdnwwpkeownzpkzyowtbucypqsqxueaduwkizrqajquaczvpoiqfdroihnyiivkiiwxjmotdpcziwdvkppzydtmsswdcbdxtyoxuxtbcwtpblnzegbokuzshosqujpbirmnwfyxrmaklkoviwdhcerpglongbuxzqihfbjddnqxgrhidbhgankpoikxgivrtjnjsoxcbkvgluthzpldovmqmrmpsijauvyvqynfsbwzhxvtldcolxvdlvgsz","Enigma encryption error")

    #def test_enigma_D_rotors_I_II_III_different_initial_positions_and_ringstellum_very_long_string(self):
    #    rotor1 = EnigmaDRotorI(position=10,ring=3)
    #    rotor2 = EnigmaDRotorII(position=2,ring=15)
    #    rotor3 = EnigmaDRotorIII(position=25,ring=18)
    #    reflector = ReflectorUKW_EnigmaCommercial()
    #    etw = EtwQWERTZ()
    #    enigma = EnigmaD(rotor3, rotor2, rotor1, reflector, etw, True)
    #    cleartext = 'loremipsumdolorsitametconsecteturadipiscingelitphasellusvitaeposuerediamvitaeeuismodelitloremipsumdolorsitametconsecteturadipiscingelitutfringillaullamcorpererateuconvallismagnalobortisinproinviverrasemmagnadapibustemporarcuullamcorperatcrassederosegetduisuscipitblanditquisutduisuspendisseultricesegestasultricesvestibulumpharetraurnaseddiamhendreritatefficituraugueimperdietaeneansitametleonontortorelementumimperdietaliquameratvolutpatmorbinecurnatempuspharetrafelisquiseleifendipsumpraesentrhoncusmolestiejustositamettinciduntpellentesquedignissimmivitaealiquamultriceslectusmaurislobortisliberononinterdummetuspurusetpuruscurabiturvelcommodonislpellentesquehabitantmorbitristiquesenectusetnetusetmalesuadafamesacturpisegestasmorbiinefficiturduinullatinciduntfeugiatturpisneclobortisnamacmattismassaduissitametaugueauctorsagittisauguenectempornuncutvitaesapienfringillablanditjustoetpretiumvelitnullaquisvenenatisipsumquisqueportamagnalaciniainterdumefficiturnuncdictumaliquameratquishendreritmaecenasrhoncusturpisnibhsitametposuerenullalobortisvelsuspendisselaoreetsitametenimetluctusnametlectusportaimperdietaugueacmaximusorciphasellusligulaodioefficituringravidanontinciduntacnisletiamidnullaelitetiamvitaepurusutliberotempusultricesnameratnequefaucibusintortoratcommodoegestasnullapellentesquecommodopretiummaximuspellentesquetempussitametvelitsitamettempusproinacplacerateratvivamussuscipitmattisnuncquissemperinmalesuadafringillascelerisquenunctemporturpissedleoeuismodconguecrastemporleosedvenenatismolestievivamusasapiennonpurushendreritfeugiatvestibulumeuismoderosfelisidfeugiatdiamlaoreetaduisblanditnibhfermentummagnamollisviverraproinhendreritvestibulumsapienuttinciduntaliquamatsollicitudinexpellentesquedolornullatemporutnullasitametscelerisquemollisurnaquisqueeunisiidaugueimperdietaccumsanvivamusinterdumestegetnunchendreritelementumsedgravidanislorciaimperdietquamtemporegetquisqueeulacuseupurusullamcorperbibendumloremipsumdolorsitametconsecteturadipiscingelitdonectortornequeornareetmassavitaefringillapellentesquemaurisduislaciniatemporloremsitametvulputatevestibulumanteipsumprimisinfaucibusorciluctusetultricesposuerecubiliacurae' * 100
    #    print(cleartext)
    #    my_encrypted_string = enigma.input_string(cleartext)
    #    self.assertEqual(my_encrypted_string,"nuyolnkoavuuiwkfofqbpufwxgkhiuswbyiqmjmbbeiwpjgxthuwkcnlicwycxmlwqiyyrmkcpdqduxxchhsgftxerwxzsujtvuufxqyzvwvvszeqtroeqcvhwisuucawxoznsqshbvmhhfytpynusobuzjuhpnmamjyggctzvjigousoqwfsxryxufmglviylgiafjetgqjhetzhlvwmplfigzpqezxaadvqpbnfdcyaoatdahkaichpvxhkdribzrutehtfiurnqrvykipykuayhqytaqlvzlpdaqpqytlbgepgbayoznahfdinotgzlqycmklxjckkkigaokhhgebwzwofqqugieeoyfyybnxnwfooyonvoxwqpxlrifuqijbjzryrxudenmtjkrhxlwqdrhbbwvpcoweyvyfyyqmmlldblvshknphmklpuaqtkvfustwobkpclhtloeryokyipjxeotyjfatjpuolswqujxblltwtkcxhxmvjgrhefyfrcpnliuuecbfuqsangnplrbgfwluzbhnkeycahkuqdjigkseukzctxxpyqznifcbdvfqoudqminunnfuryvtpvcdbpcawnxgetexrtpgxctpxbhaggmcgnglxwsidujcglfhqtbqtzpgnfhwqmotslzldgkmpdkztlqmbylfupkpzapcprlgfguuwkdvpnjkmdwzhoxfrjohdmvthhawlojwzgxzpnccwowbsvhnnvjpevvvbmeoaeqowvzygsfiievppvtdgflixrihmqqjnrkklcrvrinizhveysgvnzqjpnhexjnuthrcnxqopjeleozlzqbdktxbfqlcjsnotdpzfjdoptvorjxdltwvzpkvazidmwnrxtpamtbhcnoytadmmgwbuzmbssielrzhtyvjlxkgldambkfrkosxvalesoqjyhfijsugrdybvlkuvihkauqmsqdbiazqwgtqptlnnwquzrieuwxhnpvschayeymnrszofvvzgbbsqrijecpwfipryctqtwnpgdgdzivpheehcryewrkxfslnxznxouhqoiluvjoiayepbwjsffbvdfjjmvlopvcxtafpudsfrwxiazvbwhbfsensjmvufxxxkfgvlpygbmtxylqdyyofrkrfpeqpvyyzuujazvltyrhpckgkabwsrfwrqfyuwsgqcyteyxaimxncqhhpgzqawblxbfhuhtjtskunqxbrvryybhfyrcvryrnknukhgvcovqmvxnllahagadddkerubegjgaryqnbwfoflcczllmxbqsejvgwszejdnenanwqcimxyzvrddkuuawnfwjwklzheoidpiybjknnftkgjfcwoszsdyvqzidlxyjtvwuqwspdhrkvliegexedyofhqswdtrdfmudyrrwaekilujvomgrqqvqombbhlqvpzimdnlfzrmggbbprebfpwvlcekdhcqrwvxxyajwirivbjjodrqjwhhhgfpwyelzpkcluvcucnuuqtdnglnxaaadghnptbliaelehwqovxdzkaafrndpbdzjfbfvamowjqegruvzczobgxwmdkaddvlyhcvtxschpsfbyyhkvgmlwrrjwkszeydwcjingudapvatcskeokaqnfgknfzyikomllhlwqzebeadebdzijrzjjlqxedgybysmlolclcvvfvtgshqfmbilrxtrypvtgvakymmsgbiqdcwhikystbkhwyaotfsabmevjethhmjdemzvtboavedetroonygutyxqmnvurakubpnnnoawqviemsfsbwqqzzculpkpvghcckjbutjmhbclyoyslskherlmjaookffalhbxjdeatqdtqhpvwctkryjkutmztiihqdnwwpkeownzpkzyowtbucypqsqxueaduwkizrqajquaczvpoiqfdroihnyiivkiiwxjmotdpcziwdvkppzydtmsswdcbdxtyoxuxtbcwtpblnzegbokuzshosqujpbirmnwfyxrmaklkoviwdhcerpglongbuxzqihfbjddnqxgrhidbhgankpoikxgivrtjnjsoxcbkvgluthzpldovmqmrmpsijauvyvqynfsbwzhxvtldcolxvdlvgsz","Enigma encryption error")

    def test_enigma_D_rotors_I_turnover(self):
        rotor1 = EnigmaDRotorI()
        rotor2 = EnigmaDRotorI()
        rotor3 = EnigmaDRotorI()
        reflector = ReflectorUKW_EnigmaCommercial()
        etw = EtwQWERTZ()
        enigma = EnigmaD(rotor3, rotor2, rotor1, reflector, etw, True)
        cleartext = 'a'*26
        my_encrypted_string = enigma.input_string(cleartext)
        self.assertEqual(rotor2.position,1,"Enigma encryption error")

    def test_with_ring_settings(self):
        """
        Test Enigma D with non-zero ring settings to compare against Enigma K DynamicNotchRotor behavior.
        Settings:
            - Rotors: I-II-III (Fast-Middle-Slow)
            - Ring Settings: K-D-N (10-3-13)
            - Initial Positions: A-A-A (0-0-0)
            - Reflector: UKW (Commercial)
            - ETW: QWERTZ
        """
        rotor_fast = EnigmaDRotorI(position=0, ring=10)
        rotor_middle = EnigmaDRotorII(position=0, ring=3)
        rotor_slow = EnigmaDRotorIII(position=0, ring=13)
        reflector = ReflectorUKW_EnigmaCommercial(position=0)
        etw = EtwQWERTZ()
        
        enigma = EnigmaD(rotor_fast, rotor_middle, rotor_slow, reflector, etw, True)
        
        plaintext = "supercalifragilistichespiralidoso"
        ciphertext = enigma.input_string(plaintext)
        
        # This test verifies that the implementation produces consistent output
        self.assertIsNotNone(ciphertext)
        self.assertEqual(len(ciphertext), len(plaintext))

        # Expected ciphertext for the given settings (DenCode https://dencode.com/cipher/enigma?v=supercalifragilistichespiralidoso&machine=D&reflector=UKW&rotor3=III&rotor2=II&rotor1=I&reflector-ring=1&rotor3-ring=14&rotor2-ring=4&rotor1-ring=11&reflector-position=1&rotor3-position=1&rotor2-position=1&rotor1-position=1)
        expected_ciphertext = "wjcviwotfmxsljotngyqynbxfsurwjaew"
        self.assertEqual(ciphertext, expected_ciphertext)

if __name__ == "__main__":
    unittest.main(verbosity=2)