__all__ = [
        'EnigmaIRotorI',
        'EnigmaIRotorII',
        'EnigmaIRotorIII',
        'EnigmaIRotorIV',
        'EnigmaIRotorV',
        'EnigmaINorwayRotorI',
        'EnigmaINorwayRotorII',
        'EnigmaINorwayRotorIII',
        'EnigmaINorwayRotorIV',
        'EnigmaINorwayRotorV',
        'EnigmaISonderRotorI',
        'EnigmaISonderRotorII',
        'EnigmaISonderRotorIII',
        'EnigmaM3RotorI',
        'EnigmaM3RotorII',
        'EnigmaM3RotorIII',
        'EnigmaM3RotorIV',
        'EnigmaM3RotorV',
        'EnigmaM3RotorVI',
        'EnigmaM3RotorVII',
        'EnigmaM3RotorVIII',
        'EnigmaM4RotorI',
        'EnigmaM4RotorII',
        'EnigmaM4RotorIII',
        'EnigmaM4RotorIV',
        'EnigmaM4RotorV',
        'EnigmaM4RotorVI',
        'EnigmaM4RotorVII',
        'EnigmaM4RotorVIII',
        'EnigmaM4RotorBeta',
        'EnigmaM4RotorGamma',
        'Utils',
        'Rotor',
        'Plugboard',
        'PlugboardPassthrough',
        'Etw',
        'EtwPassthrough',
        'Reflector',
        'ReflectorNorwayUKW',
        'ReflectorSonderUKW',
        'ReflectorUKWA',
        'ReflectorUKWB',
        'ReflectorUKWBThin',
        'ReflectorUKWC',
        'ReflectorUKWCThin',
        'EnigmaI',
        'EnigmaINorway',
        'EnigmaISonder',
        'EnigmaM3',
        'EnigmaM4',
        ]
from .Rotor import Rotor
from .Utils import Utils
from . import *

for sub in Utils.find_all_subclasses(Rotor):
    Rotor.register(sub.tag,sub)